DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE PACIENTE (
	CPF CHAR(11) PRIMARY KEY,
	DT_NASC DATE,
	SEXO CHAR(1) NOT NULL,
	NOME TEXT NOT NULL,
	TIPO_SANG CHAR(2)
);

CREATE TABLE TELEFONE(
	NUMERO TEXT,
	PROPRIETARIO CHAR(11) REFERENCES PACIENTE,
	PRIMARY KEY (NUMERO, PROPRIETARIO)
);

CREATE TABLE DOENCA(
	DESCRICAO TEXT,
	PORTADOR CHAR(11) REFERENCES PACIENTE,
	PRIMARY KEY (DESCRICAO, PORTADOR)
);

CREATE TABLE FUNCAO (
    ID SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL
);

CREATE TABLE ADMINISTRADOR (
    ID SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL
);

CREATE TABLE HOSPITAL (
    CNES CHAR(7) PRIMARY KEY,
    NOME TEXT NOT NULL,
    ADM SERIAL NOT NULL,
    FOREIGN KEY (ADM) REFERENCES ADMINISTRADOR
);

CREATE TABLE SALA (
    ID SERIAL PRIMARY KEY,
    NUMERO SERIAL,
    HOSPITAL CHAR(7),
    FOREIGN KEY (HOSPITAL) REFERENCES HOSPITAL
);

CREATE TABLE FUNCINARIO (
    MATRICULA SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    FUNC SERIAL NOT NULL,
    FOREIGN KEY (FUNC) REFERENCES FUNCAO
);

CREATE TABLE MEDICO (
    CRM CHAR(9) PRIMARY KEY
);

CREATE TABLE ENFERMEIRO(
    CODIGO SERIAL PRIMARY KEY
);

CREATE TABLE ESPECIALIDADE(
    ID SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL
);

CREATE TABLE PROFISSIONAL_SAUDE (
	CPF CHAR(11) PRIMARY KEY,
    NOME TEXT NOT NULL,
    TIPO CHAR(1), -- M ou E
    CRM_MED CHAR(9) REFERENCES MEDICO ON DELETE SET NULL,
    COD_ENF INTEGER REFERENCES ENFERMEIRO ON DELETE SET NULL,
);

CREATE TABLE PROF_SAUDE_HOSP (
	CPF_PROF CHAR(11) REFERENCES PROFISSIONAL_SAUDE,
	CNES_HOSP CHAR(7) REFERENCES HOSPITAL,
	PRIMARY KEY (CPF_PROF, CNES_HOSP)
);

CREATE TABLE TIPO_PROC (
	ID SERIAL PRIMARY KEY,
	NOME TEXT NOT NULL
);

CREATE TABLE ENTRADA (
	CODIGO SERIAL PRIMARY KEY,
	DATA TIMESTAMP,
	CPF_PAC CHAR(11) REFERENCES PACIENTE,
	CNES_HOSP CHAR(7) REFERENCES HOSPITAL
);

CREATE TABLE PROCEDIMENTO (
	CODIGO SERIAL PRIMARY KEY,
	ID_TIPO SERIAL REFERENCES TIPO_PROC,
	COD_ENTR SERIAL REFERENCES ENTRADA
);

-- TABLAS RELACIONAIS
CREATE TABLE FUNC_HOSP (
    CNES_HOSP CHAR(7) REFERENCES HOSPITAL,
    MATR_FUNC SERIAL REFERENCES FUNCINARIO,
    PRIMARY KEY (CNES_HOSP, MATR_FUNC)
);

CREATE TABLE PROF_PROC (
	COD_PROC SERIAL REFERENCES PROCEDIMENTO,
	COD_PROF CHAR(11) REFERENCES PROFISSIONAL_SAUDE,
	PRIMARY KEY (COD_PROF,COD_PROC)
);

CREATE TABLE MEDICO_ESPEC (
    CRM_MED CHAR(9) REFERENCES MEDICO,
    ID_SPEC SERIAL REFERENCES ESPECIALIDADE,
    PRIMARY KEY (CRM_MED, ID_SPEC)
);

INSERT INTO MEDICO(CRM) VALUES ('1234567DF');
INSERT INTO ENFERMEIRO(CODIGO) VALUES (1);
INSERT INTO PROFISSIONAL_SAUDE(CPF, NOME, TIPO, CRM_MED, COD_ENF) VALUES ('03191571647', 'CARLOS', 'M', '1234567DF', NULL);
